#!/usr/bin/env python3
"""Regenerates Nmkoder/BinFiles/iso639.csv, the language table Aliases.cs reads from bin.

Run by hand when the ISO registers move; the output is committed, so builds need neither
network access nor Python. Requires: pip install pycountry langcodes language_data

Columns match what Aliases.LoadLangsFromCsv expects - family, English name, native name,
then three code fields it strips empties from and matches against a stream's language tag:

    Family,English Name,Native Name,ISO 639-1,ISO 639-2/T,ISO 639-2/B

Rows carrying an ISO 639-1 code are emitted first, since lookup returns the first row
holding a matching code. No code is currently claimed by two languages - the generator
prints a note if that ever changes - so the ordering is about which row wins if one is.
"""

import csv
import re
import sys
from importlib.metadata import version
from pathlib import Path

import pycountry
import langcodes

OUT = Path(__file__).resolve().parents[2] / "Nmkoder" / "BinFiles" / "iso639.csv"

HEADER_NOTES = [
    "# ISO 639 language table used by Nmkoder to name audio and subtitle tracks.",
    "# Generated by .github/scripts/gen-iso639.py - edit that, not this file.",
    "#",
    "# Sources: ISO 639-3 register via pycountry {pycountry_ver}, native names (autonyms)",
    "# via langcodes/language_data {langcodes_ver}, which draws on Unicode CLDR.",
    "#",
    "# The family column is intentionally blank: no register maps languages to families,",
    "# and Aliases.cs stores the field without ever reading it. Kept for column layout.",
]


# The register qualifies names with era and scope notes - "Modern Greek (1453-)", "Malay
# (macrolanguage)" - which read badly in a track list. Drop the trailing note, keeping the
# name itself: "Modern Greek", "Malay".
QUALIFIER = re.compile(r"\s*\((?:macrolanguage|[^()]*\b\d{3,4}\b[^()]*)\)$", re.IGNORECASE)


def english_name(lang) -> str:
    name = getattr(lang, "common_name", None) or lang.name
    return QUALIFIER.sub("", name).strip() or name


def native_name(lang, english: str) -> str:
    """CLDR autonym, or the English name when unknown - Aliases hides the duplicate."""
    # und, mul, zxx and mis are placeholders, not languages; CLDR's rendering of them
    # ("Unknown language" for und) only adds noise next to the English name.
    if getattr(lang, "type", "") == "S":
        return english

    for code in (getattr(lang, "alpha_2", None), lang.alpha_3):
        if not code:
            continue
        try:
            autonym = langcodes.Language.get(code).autonym()
        except Exception:
            continue
        if autonym and autonym.strip():
            return autonym.strip()
    return english


def build_rows():
    rows = []
    for lang in pycountry.languages:
        alpha_2 = getattr(lang, "alpha_2", "") or ""
        alpha_3 = lang.alpha_3
        biblio = getattr(lang, "bibliographic", "") or ""
        english = english_name(lang)
        rows.append([
            "",                       # family - see the header note
            english,
            native_name(lang, english),
            alpha_2,
            alpha_3,
            biblio,
        ])

    # Rows with a 639-1 code are the languages a media file is most likely tagged with.
    rows.sort(key=lambda r: (r[3] == "", r[1].lower()))
    return rows


def report_collisions(rows) -> None:
    seen = {}
    for row in rows:
        for code in (c for c in row[3:6] if c):
            if code in seen:
                print(f"  note: {code!r} claimed by {seen[code]!r} and {row[1]!r}; "
                      f"{seen[code]!r} wins the lookup", file=sys.stderr)
            else:
                seen[code] = row[1]
    print(f"  {len(seen)} distinct codes", file=sys.stderr)


def main() -> None:
    rows = build_rows()
    report_collisions(rows)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="\n") as handle:
        for note in HEADER_NOTES:
            handle.write(note.format(pycountry_ver=version("pycountry"),
                                     langcodes_ver=version("langcodes")) + "\n")
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["Family", "English Name", "Native Name",
                         "ISO 639-1", "ISO 639-2/T", "ISO 639-2/B"])
        writer.writerows(rows)

    print(f"  wrote {len(rows)} languages to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
